# This is the config file for the fgt stat checker script.
# updated 15 feb 23
fgtconfig:
    fgt_ip: "x.x.x.x"
    fgt_admin: "admin"
    fgt_password: "password"
    fgt_port: "22"

script_file_cfg:
    log_file: "fgt_stat_file.txt"
    command_file_path: "/Users/bobsmith/fgtdc"
    command_file: "fgtdc_commands.log"
    log_path: "/Users/bobsmith/fgtdc/logs/"
    file_limit: "100000"
    dir_limit: "100000000"
