# This is the config file for the fgt stat checker script.
# 
fgtconfig:
    fgt_ip: "x.x.x.x"
    fgt_admin: "admin"
    fgt_password: "password"
    fgt_port: "22"

script_file_cfg:
    log_file: "fgtdc_diag.log"
    command_file_path: "/<changeme>/FGTDC-main"
    command_file: "fgtdc_commands.log"
    log_path: "/<changeme>/FGTDC-main/logs/"
    file_limit: "100000"
    dir_limit: "100000000"

debug_config:
    debug_flag: "DEBUG"
    debug_file: "fgtdc_debug.log"
    debug_path: "/Users/andyfaulkner/Documents/Python/python-ssh/FGTDC/logs/"
    debug_log_flag: "Y" # Y for logging to file N to turn off.
